name: Heartbeat Test

on:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Heartbeat
        run: |
          echo "GitHub schedule is alive"
          date
