name: Test GitHub Actions

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Thong bao bat dau
        run: echo "GitHub Actions da bat dau chay"

      - name: Kiem tra Python
        run: python --version

      - name: Thong bao thanh cong
        run: echo "Chay thanh cong tren GitHub Actions"
